# Generated by Django 3.0.8 on 2020-07-11 07:53
from django.db import migrations, models


def create_data(apps, schema_editor):
    Convo = apps.get_model('phanhooapi', 'Convo')
    Convo(key='111', author='Lio Messi', title="Elon Musk will be the richest man in the world", 
        image="", content="", rooms="", followers="Diego Ramirez", score=0, upvotes=0, downvotes=0).save()



class Migration(migrations.Migration):
    dependencies = [
        ('phanhooapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convo',
            name='content',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='convo',
            name='downvotes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='convo',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='convo_followers', to='phanhooapi.User'),
        ),
        migrations.AlterField(
            model_name='convo',
            name='image',
            field=models.CharField(blank=True, max_length=200, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='convo',
            name='posts',
            field=models.ManyToManyField(blank=True, null=True, to='phanhooapi.Post'),
        ),
        migrations.AlterField(
            model_name='convo',
            name='rooms',
            field=models.ManyToManyField(blank=True, null=True, to='phanhooapi.Room'),
        ),
        migrations.AlterField(
            model_name='convo',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='convo',
            name='upvotes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='downvotes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='upvotes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='room',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='room_followers', to='phanhooapi.User'),
        ),
        migrations.AlterField(
            model_name='room',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_followers_+', to='phanhooapi.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_following_+', to='phanhooapi.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        # migrations.RunPython(create_data),
    ]