# Generated by Django 3.0.8 on 2020-07-15 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phanhooapi', '0002_auto_20200711_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convo',
            name='posts',
        ),
        migrations.AddField(
            model_name='convo',
            name='downvoters',
            field=models.ManyToManyField(blank=True, related_name='downvoters', to='phanhooapi.User'),
        ),
        migrations.AddField(
            model_name='convo',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoters', to='phanhooapi.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='convo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='phanhooapi.Convo'),
        ),
        migrations.AlterField(
            model_name='convo',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='convo_followers', to='phanhooapi.User'),
        ),
        migrations.AlterField(
            model_name='convo',
            name='image',
            field=models.CharField(blank=True, max_length=256, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='convo',
            name='rooms',
            field=models.ManyToManyField(blank=True, to='phanhooapi.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='room_followers', to='phanhooapi.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_user_followers_+', to='phanhooapi.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='_user_following_+', to='phanhooapi.User'),
        ),
    ]
