# Generated by Django 3.0.8 on 2020-07-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phanhooapi', '0003_auto_20200714_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(blank=True, max_length=2048, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='convo',
            name='content',
            field=models.CharField(blank=True, max_length=2048, verbose_name='Content'),
        ),
    ]
