# Generated by Django 3.0.8 on 2020-07-15 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phanhooapi', '0004_auto_20200714_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='convo',
            name='mainroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_room', to='phanhooapi.Room'),
        ),
    ]
