# Generated by Django 3.0.8 on 2020-07-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phanhooapi', '0006_auto_20200714_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=256, verbose_name='Key')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('tag_url', models.CharField(max_length=512, verbose_name='URL')),
            ],
        ),
    ]
