# Generated by Django 3.0.8 on 2020-07-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phanhooapi', '0008_auto_20200716_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='convo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='convo_tags', to='phanhooapi.Tag'),
        ),
        migrations.AddField(
            model_name='room',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='room_tags', to='phanhooapi.Tag'),
        ),
    ]
