# Generated by Django 3.0.8 on 2020-07-23 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phanhooapi', '0009_auto_20200716_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convo',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='room',
            name='tags',
        ),
        migrations.AlterField(
            model_name='convo',
            name='downvoters',
            field=models.ManyToManyField(blank=True, related_name='downvoters_convo', to='phanhooapi.User'),
        ),
        migrations.AlterField(
            model_name='convo',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='follower_convo', to='phanhooapi.User'),
        ),
        migrations.AlterField(
            model_name='convo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags_convo', to='phanhooapi.Tag'),
        ),
        migrations.AlterField(
            model_name='convo',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoters_convo', to='phanhooapi.User'),
        ),
        migrations.AlterField(
            model_name='post',
            name='convo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='phanhooapi.Convo'),
        ),
        migrations.AlterField(
            model_name='room',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='phanhooapi.User'),
        ),
        migrations.AlterField(
            model_name='room',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='phanhooapi.User'),
        ),
    ]
