# Generated by Django 3.0.8 on 2020-07-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phanhooapi', '0010_auto_20200722_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convo',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='convo',
            name='upvotes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='post',
            name='downvoters',
            field=models.ManyToManyField(blank=True, related_name='downvoters_reply', to='phanhooapi.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoters_reply', to='phanhooapi.User'),
        ),
    ]
