# Generated by Django 3.0.8 on 2020-07-31 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phanhooapi', '0011_auto_20200723_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convo',
            name='mainroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms_convo', to='phanhooapi.Room'),
        ),
    ]
