# Generated by Django 3.0.8 on 2020-07-31 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phanhooapi', '0012_auto_20200731_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convo',
            name='mainroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_convos', to='phanhooapi.Room'),
        ),
    ]
